version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: pgpwd
      #PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
        #volumes:
        #  - ./volumes/var/lib/postgresql:/var/lib/postgresql

